### ISSUE TITLE
part3 and part4 link failed

### ISSUE THREAD

**Issue by vkjuju** [rcruicks/bluemix-experience-workshops#1]
Thanks for sharing, Could you please send part3 and part4 links to me ? Thnaks
joeyangx@yahho.com

**Comment by rcruicks** [comment]
thanks for working through this workshop and pointing out the broken links - I hope you have some fun, and learned how to drive the IBM Cloud environment to get IOT and NodeRED working.

the links to parts 3 & 4 have been removed from the developerWorks library after the IBM Code site was revamped as IBM Developer. 

A much updated, and more detailed IOT with Arduino and NodeRED workshop is available at https://github.com/binnes/esp8266Workshop  

I have updated the content this repo to reflect that too

**Comment by vkjuju** [comment]
Thanks for your response, as I have a grove gsr on arduino yun, my plan is training those data on watson studio and classify our emotions(regular, nervous, deep breath, hungry) , then pass it to tjbot to say something, have you got a similar case/recipe ? Thanks

**Comment by rcruicks** [comment]
I don't know of anything that links the speech to text, tone analyzer, and a GSR datastream capture -- that could be a cool new thing -- sounds a bit like a lie-detector.
the sample nodejs app for ToneAnalyzer may help (https://github.com/watson-developer-cloud/tone-analyzer-nodejs).
But I'd start with node-red, with the browser utils (https://flows.nodered.org/node/node-red-contrib-browser-utils) to make it fairly easy to capture audio and feed into a Speech to Text service, then run through the tone analyzer. you can capture the GSR data at the same time, recording the time sequence, then correlate the GSR activity with the tone outputs. add text to speech, and play back through the browser

Then convert the audio into local audio capture with TJBot microphone (https://flows.nodered.org/node/node-red-contrib-micropi can help with a USB mic) and push the Text to Speech audio to the Pi speaker.

**Comment by vkjuju** [comment]
Thanks for prompt response, yes, it's like a lie detector, we can do it for emotion detection as well...To make my life easier,first of all,  we'd like to collect grove gsr signal from arduino yun and sent it to node-red(cloudant), it's something like your post(https://github.com/rcruicks/bluemix-experience-workshops/blob/master/Bluemix-Experience-Workshops-V6.md), but it's from simulater, have you got any sample from a real arduino ?
